name: brickbit
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  build_command: bash -c 'export COMPOSER_ALLOW_SUPERUSER=1 && composer install --no-dev --optimize-autoloader --ignore-platform-req=php --ignore-platform-req=ext-* --no-scripts && mkdir -p storage/{app,framework,logs} storage/framework/{cache,sessions,views} storage/framework/cache/data bootstrap/cache && chmod -R 755 storage bootstrap/cache'
  run_command: bash -c 'php artisan optimize:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && vendor/bin/heroku-php-apache2 -C .nginx.conf public/'
  environment_slug: php
  env:
    - key: PHP_VERSION
      value: "8.2"
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: APP_NAME
    value: "BrickBit.net"
  - key: APP_ENV
    value: "production"
  - key: APP_KEY
    value: "base64:zz1Qkl2BYRacIZlksfSquJ5A+jbfEjCWc/cZzJ11iRk="
    scope: RUN_TIME
    type: SECRET
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: "https://${APP_DOMAIN}"
  - key: FAKE_NOTIFICATIONS
    value: "false"
  - key: L5_SWAGGER_GENERATE_ALWAYS
    value: "false"
  - key: MAIN_ACCOUNT_ID
    value: "1003"
  - key: SESSION_COOKIE
    value: "bh_session"
  - key: SESSION_DOMAIN
    value: ".${APP_DOMAIN}"
  - key: LOG_CHANNEL
    value: "stderr"
  - key: LOG_LEVEL
    value: "info"
  - key: DB_CONNECTION
    value: "mysql"
  - key: DB_HOST
    value: "${db.HOSTNAME}"
  - key: DB_PORT
    value: "${db.PORT}"
  - key: DB_DATABASE
    value: "${db.DATABASE}"
  - key: DB_USERNAME
    value: "${db.USERNAME}"
  - key: DB_PASSWORD
    value: "${db.PASSWORD}"
  - key: CACHE_DRIVER
    value: "file"
  - key: SESSION_DRIVER
    value: "file"
  - key: QUEUE_DRIVER
    value: "sync"

databases:
- name: db
  engine: MYSQL
  version: "8"
